# Generated by Django 3.1.4 on 2021-01-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('long-text', 'Long Text'), ('number', 'Number'), ('url', 'Url'), ('choose-from-list', 'Choose from List')], default='text', max_length=250),
        ),
        migrations.CreateModel(
            name='RecordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('child_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_record', to='home.record')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_record', to='home.record')),
            ],
        ),
    ]
