# Generated by Django 3.1.4 on 2021-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210123_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfield',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
