# Generated by Django 3.1.4 on 2021-01-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210123_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrelation',
            name='list_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_field', to='home.listfield'),
        ),
        migrations.AddField(
            model_name='recordrelation',
            name='relation_type',
            field=models.CharField(choices=[('choose-from-list', 'Choose from list'), ('embed', 'Embed'), ('tag', 'Tag')], default='active', max_length=25),
        ),
    ]
