# Generated by Django 3.1.4 on 2020-12-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_listfield_recordfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listfield',
            old_name='name',
            new_name='field_label',
        ),
        migrations.RenameField(
            model_name='listfield',
            old_name='type',
            new_name='field_type',
        ),
    ]
