# Generated by Django 3.1.4 on 2020-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201227_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfield',
            name='field_id',
            field=models.CharField(default='1234567890', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listfield',
            name='required',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
