# Generated by Django 3.1.4 on 2020-12-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201227_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='fields',
        ),
    ]
