# Generated by Django 3.1.4 on 2020-12-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_list_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfield',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
