# Generated by Django 3.1.4 on 2020-12-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_listfield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfield',
            name='primary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
