# Generated by Django 3.1.4 on 2021-01-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210102_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfield',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list', to='home.list'),
        ),
        migrations.AlterField(
            model_name='recordfield',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='home.record'),
        ),
    ]
