# Generated by Django 3.1.4 on 2021-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210103_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
