# Generated by Django 3.1.4 on 2021-01-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210103_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfield',
            name='primary',
            field=models.BooleanField(null=True),
        ),
    ]
