# Generated by Django 3.1.4 on 2021-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210103_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfield',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
